-- D1 seed data — generated by scripts/generate-d1-seed.ts
-- Run: npx wrangler d1 execute rallyeclub-klostertal-db --file=scripts/d1-seed.sql --remote

DELETE FROM photos;
DELETE FROM albums;
DELETE FROM events;
DELETE FROM posts;

-- Posts
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('jahreshauptversammlung-2019', 'Jahreshauptversammlung 2019', 'Am 22.März fand wieder unsere Jahreshauptversammlung statt.', 'Am 22.März fand wieder unsere Jahreshauptversammlung statt.

Zusätzlich gab es zuvor einen Wettbewerb im Luftdruckschießen.

Hier die Ergebnisse!

**Damenwertung:**

1.Platz  Martina Zögernitz

2.Platz Jessica Hohenwarter

**Herrenwertung:**

1.Platz Kevin Niederegger

2.Platz Christian Breuss

3.Platz Manuel Schuler', NULL, '2019-03-22');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('autoslalom-st-gallenkirch-mai-2017', 'Autoslalom St. Gallenkirch · 07. Mai 2017', '[Ergebnisse als PDF herunterladen](/pdf/Infos-Autoslalom-St.-Gallenkirch.pdf)', '**[Ergebnisse als PDF herunterladen](/pdf/Infos-Autoslalom-St.-Gallenkirch.pdf)**', '/images/Autoslalom.jpg', '2017-05-07');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('autoslalom-st-gallenkirch-2017-rueckblick', 'Autoslalom St. Gallenkirch 2017', 'Liebe Motorsportfreunde, am 7 Mai 2017 findet wieder unser Autoslalom in St Gallenkirch ( Valliserabahn ) statt ! Auf euer kommen freut sich der Rallyeclub Klostertal', 'Liebe Motorsportfreunde, am 7 Mai 2017 findet wieder unser Autoslalom in St Gallenkirch ( Valliserabahn ) statt ! Auf euer kommen freut sich der Rallyeclub Klostertal', '/images/Autoslalom.jpg', '2017-05-08');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('slalom-st-gallenkirch-vorankuendigung', 'Slalom St. Gallenkirch — Vorankündigung', 'Der Rallyeclub Klostertal kündigt den Autoslalom in St. Gallenkirch an. Details und Uhrzeit folgen rechtzeitig auf dieser Seite.', '## Autoslalom St. Gallenkirch

Der Rallyeclub Klostertal lädt alle Motorsportfreunde herzlich zum nächsten Autoslalom in St. Gallenkirch ein.

**Ort:** Parkplatz Valiserabahn, St. Gallenkirch
**Klassen:** Serie, Spezial, Junioren

Nähere Infos zu Nennung, Zeitplan und Ablauf folgen in Kürze. Auf Dein Kommen freut sich der Rallyeclub Klostertal.', '/images/Vorank%C3%BCndigung.jpg', '2017-04-01');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('kartfahren', 'Kartfahren', 'Gemeinsames Kartfahren des Rallyeclub Klostertal — alle Bilder und Runden-Highlights.', '## Kartfahren

Ein sportlicher Abend auf der Kartbahn mit den Mitgliedern des Rallyeclub Klostertal.

![Kartfahren](/images/Bericht-Kartfahren-Bild.png)', '/images/Bericht-Kartfahren-Bild.png', '2016-06-10');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('st-gallenkirch-2016-ergebnisse-gesamt', 'St. Gallenkirch 2016 · Ergebnisse Gesamt', '[Ergebnisse als PDF herunterladen](/pdf/St.GallenkirchErgebnisse2016.pdf)', '**[Ergebnisse als PDF herunterladen](/pdf/St._Gallenkirch_Ergebnisse_2016.pdf)**', NULL, '2016-05-10');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('autoslalom-st-gallenkirch-2016', 'Autoslalom St. Gallenkirch 2016', 'Am 8. Mai 2016 findet unser Autoslalom in St. Gallenkirch (Parkplatz Valiserabahn) statt.', 'Am 8. Mai 2016 findet unser Autoslalom in St. Gallenkirch (Parkplatz Valiserabahn) statt.

Auf Euer kommen freut sich im Namen des ganzen Rallyeclub Team

Obmann Christoph Schuler', NULL, '2016-05-08');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('autoslalom-st-gallenkirch-ersatztermin-latschau', 'Autoslalom St. Gallenkirch — Ersatztermin Latschau', 'Am 3. Mai fand erstmals der Autoslalom in St. Gallenkirch statt. Der Rallyeclub Klostertal bedankt sich bei allen Funktionären, Zuschauern und natürlich auch bei den Fahrern. Wir …', 'Am 3. Mai fand erstmals der Autoslalom in St. Gallenkirch statt. Der Rallyeclub Klostertal bedankt sich bei allen Funktionären, Zuschauern und natürlich auch bei den Fahrern. Wir freuen uns auf weitere Veranstaltungen.', NULL, '2014-06-15');
INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES ('resultate-st-gallenkirch-2015', 'Resultate St. Gallenkirch 2015', '[Ergebnisse als PDF herunterladen](/pdf/ResultateSt.GallenkirchGesamt.pdf)', '**[Ergebnisse als PDF herunterladen](/pdf/Resultate_St._Gallenkirch_Gesamt.pdf)**', NULL, '2015-05-10');

-- Albums
INSERT INTO albums (slug, title, description, cover_image, date) VALUES ('jahreshauptversammlung-2016', 'Jahreshauptversammlung 2016', 'Impressionen der Jahreshauptversammlung 2016 des Rallyeclub Klostertal.', '/uploads/galerie/jahreshauptversammlung-2016/JHV2.JPG', '2016-03-18');
INSERT INTO albums (slug, title, description, cover_image, date) VALUES ('autoslalom-roethis-ostermontag-2015', 'Autoslalom Röthis — Ostermontag 2015', 'Fotos vom Autoslalom am Ostermontag 2015 in Röthis.', '/uploads/galerie/autoslalom-roethis-ostermontag-2015/IMG-20150407-WA0008.jpg', '2015-04-06');
INSERT INTO albums (slug, title, description, cover_image, date) VALUES ('autoslalom-st-gallenkirch-2015', 'Autoslalom St. Gallenkirch 2015', 'Impressionen vom Autoslalom St. Gallenkirch am 5. Mai 2015.', '/uploads/galerie/autoslalom-st-gallenkirch-2015/2015-05-05_15.09.00.jpg', '2015-05-05');
INSERT INTO albums (slug, title, description, cover_image, date) VALUES ('bowlen-im-strike-bludenz-2016', 'Bowlen im Strike Bludenz', 'Gemütlicher Abend im Strike Bludenz im März 2016.', '/uploads/galerie/bowlen-im-strike-bludenz-2016/Bowlen_24.jpg', '2016-03-05');
INSERT INTO albums (slug, title, description, cover_image, date) VALUES ('jahreshauptversammlung-2013', 'Jahreshauptversammlung 2013', 'Rückblick auf die Jahreshauptversammlung 2013.', '/uploads/galerie/jahreshauptversammlung-2013/SAM_2195.JPG', '2013-03-22');
INSERT INTO albums (slug, title, description, cover_image, date) VALUES ('dreikoenigsfest-2013', 'Dreikönigsfest 2013', 'Impressionen vom Dreikönigsfest 2013.', '/uploads/galerie/dreikoenigsfest-2013/SAM_0895.JPG', '2013-01-06');
INSERT INTO albums (slug, title, description, cover_image, date) VALUES ('gala-abend-2016', 'Gala Abend 2016', 'Der Gala-Abend des Rallyeclub Klostertal, November 2016.', '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0004.jpg', '2016-11-27');

-- Photos
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/jahreshauptversammlung-2016/JHV2.JPG', NULL, 0 FROM albums WHERE slug = 'jahreshauptversammlung-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/jahreshauptversammlung-2016/JHV3.JPG', NULL, 1 FROM albums WHERE slug = 'jahreshauptversammlung-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/jahreshauptversammlung-2016/JHV4_(1).JPG', NULL, 2 FROM albums WHERE slug = 'jahreshauptversammlung-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-roethis-ostermontag-2015/IMG-20150407-WA0008.jpg', NULL, 0 FROM albums WHERE slug = 'autoslalom-roethis-ostermontag-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-roethis-ostermontag-2015/IMG-20150407-WA0018.jpg', NULL, 1 FROM albums WHERE slug = 'autoslalom-roethis-ostermontag-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-roethis-ostermontag-2015/IMG-20150407-WA0034.jpg', NULL, 2 FROM albums WHERE slug = 'autoslalom-roethis-ostermontag-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-roethis-ostermontag-2015/IMG-20150407-WA0035.jpg', NULL, 3 FROM albums WHERE slug = 'autoslalom-roethis-ostermontag-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-roethis-ostermontag-2015/IMG-20150410-WA0000.jpg', NULL, 4 FROM albums WHERE slug = 'autoslalom-roethis-ostermontag-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-roethis-ostermontag-2015/IMG-20150410-WA0001.jpg', NULL, 5 FROM albums WHERE slug = 'autoslalom-roethis-ostermontag-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-st-gallenkirch-2015/2015-05-05_15.09.00.jpg', NULL, 0 FROM albums WHERE slug = 'autoslalom-st-gallenkirch-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/autoslalom-st-gallenkirch-2015/2015-05-05_15.09.27.jpg', NULL, 1 FROM albums WHERE slug = 'autoslalom-st-gallenkirch-2015';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/bowlen-im-strike-bludenz-2016/Bowlen_24.jpg', NULL, 0 FROM albums WHERE slug = 'bowlen-im-strike-bludenz-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/jahreshauptversammlung-2013/SAM_2195.JPG', NULL, 0 FROM albums WHERE slug = 'jahreshauptversammlung-2013';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/jahreshauptversammlung-2013/SAM_2196.JPG', NULL, 1 FROM albums WHERE slug = 'jahreshauptversammlung-2013';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/jahreshauptversammlung-2013/SAM_2197.JPG', NULL, 2 FROM albums WHERE slug = 'jahreshauptversammlung-2013';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/jahreshauptversammlung-2013/SAM_2198.JPG', NULL, 3 FROM albums WHERE slug = 'jahreshauptversammlung-2013';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/dreikoenigsfest-2013/SAM_0895.JPG', NULL, 0 FROM albums WHERE slug = 'dreikoenigsfest-2013';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0004.jpg', NULL, 0 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0005.jpg', NULL, 1 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0006.jpg', NULL, 2 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0007.jpg', NULL, 3 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0008.jpg', NULL, 4 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0009.jpg', NULL, 5 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0010.jpg', NULL, 6 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0011.jpg', NULL, 7 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0012.jpg', NULL, 8 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0013.jpg', NULL, 9 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0014.jpg', NULL, 10 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0015.jpg', NULL, 11 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0016.jpg', NULL, 12 FROM albums WHERE slug = 'gala-abend-2016';
INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, '/uploads/galerie/gala-abend-2016/IMG-20161127-WA0017.jpg', NULL, 13 FROM albums WHERE slug = 'gala-abend-2016';

-- Events
INSERT INTO events (title, date, end_date, location, description) VALUES ('Autoslalom St. Gallenkirch', '2026-05-10', NULL, 'Parkplatz Valiserabahn, St. Gallenkirch', 'Der traditionelle Autoslalom des Rallyeclub Klostertal. Klassen für Serie, Spezial und Junioren.');
INSERT INTO events (title, date, end_date, location, description) VALUES ('Jahreshauptversammlung 2026', '2026-03-21', NULL, 'Vereinslokal, Frastanz', 'Jahresrückblick, Kassabericht, Ehrungen und Ausblick auf die Saison 2026.');
INSERT INTO events (title, date, end_date, location, description) VALUES ('Kartfahren Clubausflug', '2026-06-13', NULL, 'Kartbahn Nenzing', 'Gemeinsamer Clubabend auf der Kartbahn.');
INSERT INTO events (title, date, end_date, location, description) VALUES ('Dreikönigsfest', '2026-01-06', NULL, 'Vereinslokal', 'Geselliges Beisammensein zum Saisonauftakt.');
INSERT INTO events (title, date, end_date, location, description) VALUES ('Autoslalom St. Gallenkirch 2017 (Archiv)', '2017-05-07', NULL, 'Parkplatz Valiserabahn, St. Gallenkirch', 'Archivierter Termin aus dem Jahr 2017.');
