/**
 * Generiert scripts/d1-seed.sql aus posts.json / albums.json
 * Ausführen: npx tsx scripts/generate-d1-seed.ts
 * Dann: npx wrangler d1 execute rallyeclub-klostertal-db --file=scripts/d1-seed.sql --remote
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const DATA_DIR = path.join(ROOT, "scripts", "data");
const OUT = path.join(ROOT, "scripts", "d1-seed.sql");

function esc(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return `'${String(v).replace(/'/g, "''")}'`;
}

type SeedPost = {
  slug: string;
  title: string;
  date: string;
  cover: string | null;
  excerpt: string;
  content: string;
};

type SeedAlbum = {
  slug: string;
  title: string;
  description: string | null;
  date: string | null;
  cover_image: string;
  photos: string[];
};

const CONTENT_OVERRIDES: Record<string, Partial<SeedPost>> = {
  "slalom-st-gallenkirch-vorankuendigung": {
    title: "Slalom St. Gallenkirch — Vorankündigung",
    excerpt:
      "Der Rallyeclub Klostertal kündigt den Autoslalom in St. Gallenkirch an. Details und Uhrzeit folgen rechtzeitig auf dieser Seite.",
    content: `## Autoslalom St. Gallenkirch

Der Rallyeclub Klostertal lädt alle Motorsportfreunde herzlich zum nächsten Autoslalom in St. Gallenkirch ein.

**Ort:** Parkplatz Valiserabahn, St. Gallenkirch
**Klassen:** Serie, Spezial, Junioren

Nähere Infos zu Nennung, Zeitplan und Ablauf folgen in Kürze. Auf Dein Kommen freut sich der Rallyeclub Klostertal.`,
  },
  kartfahren: {
    excerpt: "Gemeinsames Kartfahren des Rallyeclub Klostertal — alle Bilder und Runden-Highlights.",
    content: `## Kartfahren

Ein sportlicher Abend auf der Kartbahn mit den Mitgliedern des Rallyeclub Klostertal.

![Kartfahren](/images/Bericht-Kartfahren-Bild.png)`,
  },
};

const lines: string[] = [
  "-- D1 seed data — generated by scripts/generate-d1-seed.ts",
  "-- Run: npx wrangler d1 execute rallyeclub-klostertal-db --file=scripts/d1-seed.sql --remote",
  "",
  "DELETE FROM photos;",
  "DELETE FROM albums;",
  "DELETE FROM events;",
  "DELETE FROM posts;",
  "",
];

// Posts
const posts: SeedPost[] = JSON.parse(fs.readFileSync(path.join(DATA_DIR, "posts.json"), "utf8"));
lines.push("-- Posts");
for (const raw of posts) {
  const p = { ...raw, ...CONTENT_OVERRIDES[raw.slug] };
  const slug = esc(p.slug ?? raw.slug);
  const title = esc(p.title ?? raw.title);
  const excerpt = esc(p.excerpt ?? raw.excerpt ?? null);
  const content = esc(p.content ?? raw.content);
  const cover = esc(p.cover ?? raw.cover ?? null);
  const date = esc(p.date ?? raw.date);
  lines.push(
    `INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES (${slug}, ${title}, ${excerpt}, ${content}, ${cover}, ${date});`
  );
}
lines.push("");

// Albums
const albums: SeedAlbum[] = JSON.parse(fs.readFileSync(path.join(DATA_DIR, "albums.json"), "utf8"));
lines.push("-- Albums");
for (const a of albums) {
  lines.push(
    `INSERT INTO albums (slug, title, description, cover_image, date) VALUES (${esc(a.slug)}, ${esc(a.title)}, ${esc(a.description)}, ${esc(a.cover_image)}, ${esc(a.date)});`
  );
}
lines.push("");

// Photos — reference albums by slug subquery
lines.push("-- Photos");
for (const a of albums) {
  a.photos.forEach((url, i) => {
    lines.push(
      `INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, ${esc(url)}, NULL, ${i} FROM albums WHERE slug = ${esc(a.slug)};`
    );
  });
}
lines.push("");

// Events
lines.push("-- Events");
const events = [
  { title: "Autoslalom St. Gallenkirch", date: "2026-05-10", end_date: null, location: "Parkplatz Valiserabahn, St. Gallenkirch", description: "Der traditionelle Autoslalom des Rallyeclub Klostertal. Klassen für Serie, Spezial und Junioren." },
  { title: "Jahreshauptversammlung 2026", date: "2026-03-21", end_date: null, location: "Vereinslokal, Frastanz", description: "Jahresrückblick, Kassabericht, Ehrungen und Ausblick auf die Saison 2026." },
  { title: "Kartfahren Clubausflug", date: "2026-06-13", end_date: null, location: "Kartbahn Nenzing", description: "Gemeinsamer Clubabend auf der Kartbahn." },
  { title: "Dreikönigsfest", date: "2026-01-06", end_date: null, location: "Vereinslokal", description: "Geselliges Beisammensein zum Saisonauftakt." },
  { title: "Autoslalom St. Gallenkirch 2017 (Archiv)", date: "2017-05-07", end_date: null, location: "Parkplatz Valiserabahn, St. Gallenkirch", description: "Archivierter Termin aus dem Jahr 2017." },
];
for (const e of events) {
  lines.push(
    `INSERT INTO events (title, date, end_date, location, description) VALUES (${esc(e.title)}, ${esc(e.date)}, ${esc(e.end_date)}, ${esc(e.location)}, ${esc(e.description)});`
  );
}
lines.push("");

fs.writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`✓ Geschrieben: scripts/d1-seed.sql (${lines.length} Zeilen)`);
