/**
 * Wandelt scripts/data/posts.json + albums.json + die fest verdrahteten Events
 * in eine pure SQL-Datei um (db/seed-data.sql).
 *
 * Hintergrund: Postgres in Coolify ist nicht direkt von außen erreichbar.
 * Die generierte Datei kann im Coolify-Postgres-Terminal eingefügt werden:
 *   1) cd /, dann: psql -U rck -d rck
 *   2) Inhalt von db/seed-data.sql kopieren und einfügen
 *
 * Aufruf:
 *   npx tsx scripts/seed-sql.ts
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const DATA_DIR = path.join(ROOT, "scripts", "data");
const OUT = path.join(ROOT, "db", "seed-data.sql");

type SeedPost = {
  slug: string;
  title: string;
  date: string;
  cover: string | null;
  excerpt: string | null;
  content: string;
};

type SeedAlbum = {
  slug: string;
  title: string;
  description: string | null;
  date: string | null;
  cover_image: string;
  photos: string[];
};

type SeedEvent = {
  title: string;
  date: string;
  end_date: string | null;
  location: string | null;
  description: string | null;
};

function sqlString(v: string | null | undefined): string {
  if (v == null) return "NULL";
  return `'${v.replace(/'/g, "''")}'`;
}

function main(): void {
  const postsPath = path.join(DATA_DIR, "posts.json");
  const albumsPath = path.join(DATA_DIR, "albums.json");
  if (!fs.existsSync(postsPath) || !fs.existsSync(albumsPath)) {
    console.error("posts.json/albums.json fehlen — bitte zuerst `npm run scrape` ausführen.");
    process.exit(1);
  }

  const posts: SeedPost[] = JSON.parse(fs.readFileSync(postsPath, "utf8"));
  const albums: SeedAlbum[] = JSON.parse(fs.readFileSync(albumsPath, "utf8"));

  const events: SeedEvent[] = [
    { title: "Autoslalom St. Gallenkirch", date: "2026-05-10", end_date: null, location: "Parkplatz Valiserabahn, St. Gallenkirch", description: "Der traditionelle Autoslalom des Rallyeclub Klostertal. Klassen für Serie, Spezial und Junioren." },
    { title: "Jahreshauptversammlung 2026", date: "2026-03-21", end_date: null, location: "Vereinslokal, Frastanz", description: "Jahresrückblick, Kassabericht, Ehrungen und Ausblick auf die Saison 2026." },
    { title: "Kartfahren Clubausflug", date: "2026-06-13", end_date: null, location: "Kartbahn Nenzing", description: "Gemeinsamer Clubabend auf der Kartbahn." },
    { title: "Dreikönigsfest", date: "2026-01-06", end_date: null, location: "Vereinslokal", description: "Geselliges Beisammensein zum Saisonauftakt." },
    { title: "Autoslalom St. Gallenkirch 2017 (Archiv)", date: "2017-05-07", end_date: null, location: "Parkplatz Valiserabahn, St. Gallenkirch", description: "Archivierter Termin aus dem Jahr 2017." },
  ];

  const lines: string[] = [];
  lines.push("-- Generated by scripts/seed-sql.ts — re-runnable.");
  lines.push("-- ACHTUNG: TRUNCATE leert posts/albums/photos/events vollständig.");
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");
  lines.push("TRUNCATE photos, albums, posts, events RESTART IDENTITY CASCADE;");
  lines.push("");

  lines.push("-- POSTS");
  for (const p of posts) {
    const values = [
      sqlString(p.slug),
      sqlString(p.title),
      sqlString(p.excerpt),
      sqlString(p.content),
      sqlString(p.cover),
      sqlString(p.date),
    ].join(", ");
    lines.push(
      `INSERT INTO posts (slug, title, excerpt, content, cover_image, published_at) VALUES (${values});`,
    );
  }
  lines.push("");

  lines.push("-- ALBUMS + PHOTOS");
  for (const a of albums) {
    const albumValues = [
      sqlString(a.slug),
      sqlString(a.title),
      sqlString(a.description),
      sqlString(a.cover_image),
      sqlString(a.date),
    ].join(", ");
    lines.push(
      `INSERT INTO albums (slug, title, description, cover_image, date) VALUES (${albumValues});`,
    );
    for (let i = 0; i < a.photos.length; i++) {
      const url = a.photos[i];
      lines.push(
        `INSERT INTO photos (album_id, url, caption, sort_order) SELECT id, ${sqlString(url)}, NULL, ${i} FROM albums WHERE slug = ${sqlString(a.slug)};`,
      );
    }
  }
  lines.push("");

  lines.push("-- EVENTS");
  for (const e of events) {
    const values = [
      sqlString(e.title),
      sqlString(e.date),
      sqlString(e.end_date),
      sqlString(e.location),
      sqlString(e.description),
    ].join(", ");
    lines.push(
      `INSERT INTO events (title, date, end_date, location, description) VALUES (${values});`,
    );
  }
  lines.push("");

  lines.push("COMMIT;");
  lines.push("");
  lines.push(`-- Done: ${posts.length} posts, ${albums.length} albums, ${events.length} events.`);

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, lines.join("\n"), "utf8");

  console.log(`✓ ${path.relative(ROOT, OUT)} geschrieben`);
  console.log(`  ${posts.length} Beiträge, ${albums.length} Alben, ${events.length} Veranstaltungen`);
}

main();
